### ISSUE TITLE
File paths

### ISSUE THREAD

**Issue by ghost** [brianhbirch/prj-rev-bwfs-dasmoto#1]
https://github.com/brianhbirch/prj-rev-bwfs-dasmoto/blob/master/dasmoto/index.html#L12

This is what your images look like on another computer when you use an absolute path to them.

![screen shot 2017-07-16 at 12 25 25 pm](https://user-images.githubusercontent.com/7355203/28249335-ddf77e00-6a21-11e7-8751-34070368db51.png)

Use a relative file path instead, like you did for link to your stylesheet.

`./resources/images/hacksaw.jpg`

**Comment by brianhbirch** [comment]
Got it, thanks!
